version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.Primitives.Abstractions"
  schedule:
    interval: weekly
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
