<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>.net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pure.Primitives" />
    <InternalsVisibleTo Include="Pure.Primitives.Tests" />
    <InternalsVisibleTo Include="Pure.Primitives.Choices" />
    <InternalsVisibleTo Include="Pure.Primitives.Choices.Tests" />
    <InternalsVisibleTo Include="Pure.Primitives.Number.Operations" />
    <InternalsVisibleTo Include="Pure.Primitives.Number.Operations.Tests" />
    <InternalsVisibleTo Include="Pure.Primitives.Bool.Operations" />
    <InternalsVisibleTo Include="Pure.Primitives.Bool.Operations.Tests" />
    <InternalsVisibleTo Include="Pure.Primitives.String.Operations" />
    <InternalsVisibleTo Include="Pure.Primitives.String.Operations.Tests" />
    <InternalsVisibleTo Include="Pure.HashCodes" />
    <InternalsVisibleTo Include="Pure.HashCodes.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Pure.Primitives.Abstractions</PackageId>
    <RootNamespace>Pure.Primitives.Abstractions</RootNamespace>
    <AssemblyName>Pure.Primitives.Abstractions</AssemblyName>
    <Version>0.1.0</Version>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.Primitives.Abstractions</PackageProjectUrl>
  </PropertyGroup>

</Project>
