<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>.net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pure.Primitives" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Pure.Primitives.Abstractions</PackageId>
    <RootNamespace>Pure.Primitives.Abstractions</RootNamespace>
    <AssemblyName>Pure.Primitives.Abstractions</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.Primitives</PackageProjectUrl>
  </PropertyGroup>

</Project>
