<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>.net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Pure.Primitives.Abstractions</PackageId>
    <RootNamespace>Pure.Primitives.Abstractions</RootNamespace>
    <AssemblyName>Pure.Primitives.Abstractions</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.Primitives.Abstractions</PackageProjectUrl>
  </PropertyGroup>
</Project>
