name: Build and Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
    - name: Set up source
      run: dotnet nuget add source --username kudima03 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kudima03/index.json"
    - name: Package
      run: dotnet pack --configuration Release -p:PackageVersion=${{ github.ref_name }} --output .
    - name: Publish
      run: dotnet nuget push **/*.nupkg --source github